run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - dupl
    - gosec

  disable:
    # Bruit stylistique inutile
    - wsl
    - whitespace
    - wsl_v5

    # Trop strict / académique à ce stade
    - mnd
    - fieldalignment
    - prealloc
    - unparam
    - goconst
    - misspell

linters-settings:
  dupl:
    threshold: 120

issues:
  exclude-use-default: false
