##############################
# Stage 1 — Build server binary using OQS base image
##############################
FROM oqs:dev

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the worker
RUN go build -o worker ./cmd/worker/main.go

# Make worker binary executable
RUN chmod +x /app/worker

CMD ["./worker"]
