name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: read
env:
  CGO_ENABLED: "1"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: oleglod/cafe-oqs:build
    steps:
      - name: go version
        run: go version
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod download

      - name: Run Linter
        run: golangci-lint run ./...

      - name: Run unit-tests
        run: go test ./...

      - name: Run govulncheck
        run: govulncheck ./...
